// ============================================================================
// Kikoushou PWA - Type Definitions
// A vacation house room assignment and arrivals/departures tracking application
// ============================================================================

// ============================================================================
// Branded Types for Type-Safe IDs
// ============================================================================

/**
 * Branded type pattern for nominal typing.
 * Prevents accidentally mixing IDs of different entity types.
 */
declare const __brand: unique symbol;

/**
 * Creates a branded type that is structurally a string but nominally distinct.
 * Exported for consumers who need to create custom branded types.
 * @template T - The brand identifier
 */
export type Brand<T extends string> = string & { readonly [__brand]: T };

/** Type-safe Trip identifier (nanoid generated) */
export type TripId = Brand<'TripId'>;

/** Type-safe Room identifier (nanoid generated) */
export type RoomId = Brand<'RoomId'>;

/** Type-safe Person identifier (nanoid generated) */
export type PersonId = Brand<'PersonId'>;

/** Type-safe RoomAssignment identifier (nanoid generated) */
export type RoomAssignmentId = Brand<'RoomAssignmentId'>;

/** Type-safe Transport identifier (nanoid generated) */
export type TransportId = Brand<'TransportId'>;

/** Type-safe Share identifier (shorter nanoid for sharing URLs) */
export type ShareId = Brand<'ShareId'>;

// ============================================================================
// Primitive Utility Types
// ============================================================================

/**
 * ISO 8601 date string in YYYY-MM-DD format.
 * @example "2024-07-15"
 */
export type ISODateString = string;

/**
 * ISO 8601 datetime string with timezone.
 * @example "2024-07-15T14:30:00.000Z"
 */
export type ISODateTimeString = string;

/**
 * Hexadecimal color string.
 * @example "#ef4444" or "#f00"
 */
export type HexColor = string;

/**
 * Unix timestamp in milliseconds.
 * @example 1720000000000
 */
export type UnixTimestamp = number;

// ============================================================================
// Enumeration Types
// ============================================================================

/**
 * Transport event type indicating direction of travel.
 */
export type TransportType = 'arrival' | 'departure';

/**
 * Mode of transportation for arrivals and departures.
 */
export type TransportMode = 'train' | 'plane' | 'car' | 'bus' | 'other';

/**
 * Room icon type for visual identification across views.
 * Icons are from lucide-react library.
 */
export type RoomIcon =
  | 'bed-double'   // Default bedroom
  | 'bed-single'   // Single bed room
  | 'bath'         // Bathroom
  | 'sofa'         // Living room
  | 'tent'         // Tent/outdoor
  | 'caravan'      // Mobile home
  | 'warehouse'    // Garage/storage
  | 'home'         // General room
  | 'door-open'    // Entryway
  | 'baby'         // Kids room
  | 'armchair';    // Lounge

/**
 * Default room icon when none is selected.
 */
export const DEFAULT_ROOM_ICON: RoomIcon = 'bed-double';

/**
 * Supported application languages.
 */
export type Language = 'en' | 'fr';

// ============================================================================
// Base Interfaces
// ============================================================================

/**
 * Base interface for all entities with an identifier.
 */
export interface Identifiable {
  /** Unique identifier generated by nanoid */
  readonly id: string;
}

/**
 * Base interface for entities that belong to a specific trip.
 *
 * @indexing Dexie.js schema should include compound indexes:
 * - For Room: `[tripId+order]`
 * - For RoomAssignment: `[tripId+startDate]`, `[tripId+personId]`, `[tripId+roomId]`
 * - For Transport: `[tripId+datetime]`, `[tripId+personId]`, `[tripId+type]`
 */
export interface TripScoped {
  /** Foreign key reference to the parent Trip */
  readonly tripId: TripId;
}

/**
 * Represents a date range with start and end dates.
 * Used for trips and room assignments.
 *
 * @constraint startDate must be on or before endDate (validated at runtime)
 */
export interface DateRange {
  /**
   * Start date in ISO format (YYYY-MM-DD).
   * @example "2024-07-15"
   */
  startDate: ISODateString;

  /**
   * End date in ISO format (YYYY-MM-DD).
   * @example "2024-07-22"
   */
  endDate: ISODateString;
}

/**
 * Mixin for entities with creation and update timestamps.
 */
export interface WithTimestamps {
  /** Unix timestamp (ms) when the entity was created */
  readonly createdAt: UnixTimestamp;
  /** Unix timestamp (ms) when the entity was last updated */
  updatedAt: UnixTimestamp;
}

// ============================================================================
// Core Entity Interfaces
// ============================================================================

/**
 * A vacation or holiday event that groups rooms, persons, and logistics.
 *
 * @description The Trip is the root entity in Kikoushou. All other entities
 * (rooms, persons, assignments, transports) belong to a specific trip.
 *
 * @example
 * ```typescript
 * const trip: Trip = {
 *   id: 'abc123' as TripId,
 *   name: 'Summer vacation 2024',
 *   location: 'Beach house, Brittany',
 *   startDate: '2024-07-15',
 *   endDate: '2024-07-22',
 *   shareId: 'xyz789' as ShareId,
 *   createdAt: 1720000000000,
 *   updatedAt: 1720000000000,
 * };
 * ```
 */
export interface Trip extends Identifiable, WithTimestamps {
  /** Unique trip identifier */
  readonly id: TripId;

  /**
   * Display name for the trip.
   * @example "Summer vacation 2024"
   */
  name: string;

  /**
   * Optional location description.
   * @example "Beach house, Brittany"
   */
  location?: string;

  /**
   * Start date of the trip in ISO format (YYYY-MM-DD).
   * Must be on or before endDate.
   * @example "2024-07-15"
   */
  startDate: ISODateString;

  /**
   * End date of the trip in ISO format (YYYY-MM-DD).
   * Must be on or after startDate.
   * @example "2024-07-22"
   */
  endDate: ISODateString;

  /**
   * Unique identifier for sharing the trip via URL or QR code.
   * Shorter than regular IDs for convenience (10 characters).
   */
  readonly shareId: ShareId;

  /**
   * Optional description or notes for the trip.
   * Can include instructions, links (e.g., tricount), or other useful information.
   * @example "Instructions: Check-in after 3pm. Tricount: https://tricount.com/..."
   */
  description?: string;

  /**
   * Optional GPS coordinates for the trip location.
   * Used for displaying map previews on trip cards.
   * @example { lat: 48.8566, lon: 2.3522 }
   */
  coordinates?: {
    readonly lat: number;
    readonly lon: number;
  };
}

/**
 * A room or sleeping area in the vacation house.
 *
 * @description Rooms belong to a trip and can have persons assigned to them
 * for specific date ranges. The order field controls display sorting.
 *
 * @see {@link Trip} - Parent entity
 * @see {@link RoomAssignment} - Links persons to rooms
 *
 * @example
 * ```typescript
 * const room: Room = {
 *   id: 'room123' as RoomId,
 *   tripId: 'trip456' as TripId,
 *   name: 'Master bedroom',
 *   capacity: 2,
 *   description: 'King bed with ensuite bathroom',
 *   order: 0,
 * };
 * ```
 */
export interface Room extends Identifiable, TripScoped {
  /** Unique room identifier */
  readonly id: RoomId;

  /**
   * Display name for the room.
   * @example "Master bedroom"
   */
  name: string;

  /**
   * Number of beds/sleeping spots in the room.
   * Must be a positive integer (minimum: 1).
   */
  capacity: number;

  /**
   * Optional description or notes about the room.
   * @example "King bed with ensuite bathroom"
   */
  description?: string;

  /**
   * Display order for sorting rooms.
   * Lower numbers appear first. Must be a non-negative integer.
   */
  order: number;

  /**
   * Optional icon for visual identification.
   * Defaults to 'bed-double' when not specified.
   * @see {@link RoomIcon}
   * @example "bed-double"
   */
  icon?: RoomIcon;
}

/**
 * A participant in a trip.
 *
 * @description Persons are people participating in a trip. Each person has
 * a unique color for visual identification on the calendar view.
 *
 * @see {@link Trip} - Parent entity
 * @see {@link RoomAssignment} - Assigns persons to rooms
 * @see {@link Transport} - Person's arrival/departure logistics
 *
 * @example
 * ```typescript
 * const person: Person = {
 *   id: 'person123' as PersonId,
 *   tripId: 'trip456' as TripId,
 *   name: 'Marie',
 *   color: '#ef4444',
 * };
 * ```
 */
export interface Person extends Identifiable, TripScoped {
  /** Unique person identifier */
  readonly id: PersonId;

  /**
   * Display name of the person.
   * @example "Marie"
   */
  name: string;

  /**
   * Hex color code for calendar display.
   * Used to visually distinguish this person's assignments.
   * @example "#ef4444"
   */
  color: HexColor;

  /**
   * Optional stay start date (ISO format, YYYY-MM-DD).
   * When the person is expected to arrive at the trip.
   * @example "2024-07-15"
   */
  stayStartDate?: ISODateString;

  /**
   * Optional stay end date (ISO format, YYYY-MM-DD).
   * When the person is expected to leave the trip.
   * @example "2024-07-22"
   */
  stayEndDate?: ISODateString;
}

/**
 * Links a person to a room for a specific date range.
 *
 * @description Room assignments represent when a person sleeps in a specific
 * room. A person cannot be assigned to multiple rooms for overlapping dates.
 *
 * @see {@link Trip} - Parent entity
 * @see {@link Room} - The assigned room
 * @see {@link Person} - The assigned person
 *
 * @example
 * ```typescript
 * const assignment: RoomAssignment = {
 *   id: 'assign123' as RoomAssignmentId,
 *   tripId: 'trip456' as TripId,
 *   roomId: 'room789' as RoomId,
 *   personId: 'person012' as PersonId,
 *   startDate: '2024-07-15',
 *   endDate: '2024-07-19',
 * };
 * ```
 */
export interface RoomAssignment extends Identifiable, TripScoped {
  /** Unique assignment identifier */
  readonly id: RoomAssignmentId;

  /**
   * Reference to the room being assigned.
   * @see {@link Room}
   */
  roomId: RoomId;

  /**
   * Reference to the person being assigned.
   * @see {@link Person}
   */
  personId: PersonId;

  /**
   * First night of the assignment in ISO format (YYYY-MM-DD).
   * Must be within the trip's date range and on or before endDate.
   * @example "2024-07-15"
   */
  startDate: ISODateString;

  /**
   * Last night of the assignment in ISO format (YYYY-MM-DD).
   * Must be within the trip's date range and on or after startDate.
   * @example "2024-07-19"
   */
  endDate: ISODateString;
}

/**
 * An arrival or departure event for a trip participant.
 *
 * @description Transports track when and how persons arrive at or depart from
 * the trip location. They can include pickup/dropoff logistics.
 *
 * @see {@link Trip} - Parent entity
 * @see {@link Person} - The traveling person
 * @see {@link Person} - Optional driver for pickup/dropoff (driverId)
 *
 * @example
 * ```typescript
 * const transport: Transport = {
 *   id: 'trans123' as TransportId,
 *   tripId: 'trip456' as TripId,
 *   personId: 'person789' as PersonId,
 *   type: 'arrival',
 *   datetime: '2024-07-15T14:30:00.000Z',
 *   location: 'Gare Montparnasse',
 *   transportMode: 'train',
 *   transportNumber: 'TGV 8541',
 *   driverId: 'person012' as PersonId,
 *   needsPickup: true,
 *   notes: 'Platform 12',
 * };
 * ```
 */
export interface Transport extends Identifiable, TripScoped {
  /** Unique transport identifier */
  readonly id: TransportId;

  /**
   * Reference to the traveling person.
   * @see {@link Person}
   */
  personId: PersonId;

  /**
   * Whether this is an arrival or departure event.
   */
  type: TransportType;

  /**
   * Date and time of arrival/departure in ISO 8601 format with timezone.
   * @example "2024-07-15T14:30:00.000Z"
   */
  datetime: ISODateTimeString;

  /**
   * Location name (station, airport, address, etc.).
   * @example "Gare Montparnasse"
   */
  location: string;

  /**
   * Mode of transportation.
   * @example "train"
   */
  transportMode?: TransportMode;

  /**
   * Train number, flight number, or other identifier.
   * @example "TGV 8541" or "AF1234"
   */
  transportNumber?: string;

  /**
   * Reference to the person responsible for pickup/dropoff.
   * Only relevant when needsPickup is true.
   * @see {@link Person}
   */
  driverId?: PersonId;

  /**
   * Whether this transport needs someone to provide a ride.
   * When true, displays in the "upcoming pickups" section.
   */
  needsPickup: boolean;

  /**
   * Additional notes about the transport.
   * @example "Platform 12" or "Terminal 2E"
   */
  notes?: string;
}

/**
 * Application settings stored as a singleton record.
 *
 * @description Stores user preferences and application state.
 * There is exactly one AppSettings record with id='settings'.
 *
 * @example
 * ```typescript
 * const settings: AppSettings = {
 *   id: 'settings',
 *   language: 'fr',
 *   currentTripId: 'trip456' as TripId,
 * };
 * ```
 */
export interface AppSettings extends Identifiable {
  /**
   * Singleton identifier - always 'settings'.
   * @readonly
   */
  readonly id: 'settings';

  /**
   * User's preferred language.
   * @default 'fr'
   */
  language: Language;

  /**
   * ID of the last viewed trip for session restoration.
   * Undefined if no trip has been viewed yet.
   */
  currentTripId?: TripId;
}

// ============================================================================
// Form Data Types (for create/edit operations)
// ============================================================================

/**
 * Data required to create or update a Trip.
 * Excludes auto-generated fields (id, shareId, timestamps).
 *
 * @see {@link Trip}
 */
export interface TripFormData {
  /** Display name for the trip */
  name: string;
  /** Optional location description */
  location?: string;
  /** Start date in ISO format (YYYY-MM-DD) */
  startDate: ISODateString;
  /** End date in ISO format (YYYY-MM-DD) */
  endDate: ISODateString;
  /** Optional description or notes for the trip */
  description?: string;
  /** Optional GPS coordinates for the trip location */
  coordinates?: {
    readonly lat: number;
    readonly lon: number;
  };
}

/**
 * Data required to create or update a Room.
 * Excludes auto-generated fields (id, tripId, order).
 *
 * @see {@link Room}
 */
export interface RoomFormData {
  /** Display name for the room */
  name: string;
  /** Number of beds/sleeping spots (minimum: 1) */
  capacity: number;
  /** Optional description or notes */
  description?: string;
  /** Optional icon for visual identification */
  icon?: RoomIcon;
}

/**
 * Data required to create or update a Person.
 * Excludes auto-generated fields (id, tripId).
 *
 * @see {@link Person}
 */
export interface PersonFormData {
  /** Display name of the person */
  name: string;
  /** Hex color code for calendar display */
  color: HexColor;
  /** Optional stay start date (ISO format, YYYY-MM-DD) */
  stayStartDate?: ISODateString;
  /** Optional stay end date (ISO format, YYYY-MM-DD) */
  stayEndDate?: ISODateString;
}

/**
 * Data required to create or update a RoomAssignment.
 * Excludes auto-generated fields (id, tripId).
 *
 * @see {@link RoomAssignment}
 */
export interface RoomAssignmentFormData {
  /** Reference to the room being assigned */
  roomId: RoomId;
  /** Reference to the person being assigned */
  personId: PersonId;
  /** First night of the assignment (YYYY-MM-DD) */
  startDate: ISODateString;
  /** Last night of the assignment (YYYY-MM-DD) */
  endDate: ISODateString;
}

/**
 * Data required to create or update a Transport.
 * Excludes auto-generated fields (id, tripId).
 *
 * @see {@link Transport}
 */
export interface TransportFormData {
  /** Reference to the traveling person */
  personId: PersonId;
  /** Whether this is an arrival or departure */
  type: TransportType;
  /** Date and time in ISO 8601 format */
  datetime: ISODateTimeString;
  /** Location name (station, airport, etc.) */
  location: string;
  /** Mode of transportation */
  transportMode?: TransportMode;
  /** Train/flight number or other identifier */
  transportNumber?: string;
  /** Reference to the driver for pickup/dropoff */
  driverId?: PersonId;
  /** Whether pickup/dropoff is needed */
  needsPickup: boolean;
  /** Additional notes */
  notes?: string;
}

// ============================================================================
// Utility Types for Common Operations
// ============================================================================

/**
 * Union of all trip-scoped entity types.
 */
export type TripEntity = Room | Person | RoomAssignment | Transport;

/**
 * Union of all entity types in the application.
 */
export type AnyEntity = Trip | TripEntity | AppSettings;

/**
 * Extracts the ID type from an entity type.
 * @template T - The entity type
 */
export type EntityId<T extends Identifiable> = T['id'];

/**
 * Makes specified properties of T optional.
 * @template T - The base type
 * @template K - Keys to make optional
 */
export type PartialBy<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>;

/**
 * Makes specified properties of T required.
 * @template T - The base type
 * @template K - Keys to make required
 */
export type RequiredBy<T, K extends keyof T> = Omit<T, K> &
  Required<Pick<T, K>>;

/**
 * Creates a type for partial updates to an entity.
 * Preserves id and tripId as readonly, makes other fields optional.
 * @template T - The entity type extending TripScoped
 */
/**
 * Creates a type for partial updates to a trip-scoped entity.
 * Preserves id and tripId as readonly, makes other fields optional.
 * @template T - The entity type extending TripScoped
 */
export type EntityUpdate<T extends TripScoped & Identifiable> = Readonly<
  Pick<T, 'id' | 'tripId'>
> &
  Partial<Omit<T, 'id' | 'tripId'>>;

/**
 * Creates a type for partial updates to a Trip entity.
 * Preserves id as readonly, excludes shareId and createdAt from updates.
 */
export type TripUpdate = Readonly<Pick<Trip, 'id'>> &
  Partial<Omit<Trip, 'id' | 'shareId' | 'createdAt'>>;

/**
 * Default color palette for person assignment.
 * Used when automatically assigning colors to new persons.
 */
export const DEFAULT_PERSON_COLORS = [
  '#ef4444', // Red
  '#f97316', // Orange
  '#eab308', // Yellow
  '#22c55e', // Green
  '#14b8a6', // Teal
  '#3b82f6', // Blue
  '#8b5cf6', // Violet
  '#ec4899', // Pink
] as const satisfies readonly HexColor[];

/**
 * Gets a default person color by index, cycling through the palette.
 * Use this helper to avoid undefined checks with `noUncheckedIndexedAccess`.
 * @param index - The index (will be wrapped using modulo)
 * @returns A hex color from the default palette
 */
export function getDefaultPersonColor(index: number): HexColor {
  const safeIndex = Math.abs(index) % DEFAULT_PERSON_COLORS.length;
   
  return DEFAULT_PERSON_COLORS[safeIndex]!;
}

/**
 * Default application settings.
 */
export const DEFAULT_SETTINGS: AppSettings = {
  id: 'settings',
  language: 'fr',
  currentTripId: undefined,
} as const;
